// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAFfBUM4W4FNWFM1EXLtvmp6k-4Xtj0TO0',
    appId: '1:180029562035:web:688d2f6d207844385624c6',
    messagingSenderId: '180029562035',
    projectId: 'test-flutter-calculator',
    authDomain: 'test-flutter-calculator.firebaseapp.com',
    storageBucket: 'test-flutter-calculator.appspot.com',
    measurementId: 'G-M07GV796R4',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDEnNd67l9S_fzEOft_PHwlfLqGbGB_jDU',
    appId: '1:180029562035:android:d5f47b739a63c5ee5624c6',
    messagingSenderId: '180029562035',
    projectId: 'test-flutter-calculator',
    storageBucket: 'test-flutter-calculator.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyD3u-1f-YzT8tTNP9bDqe0Wlxt9TiFWyDQ',
    appId: '1:180029562035:ios:a08c49ec94da58d55624c6',
    messagingSenderId: '180029562035',
    projectId: 'test-flutter-calculator',
    storageBucket: 'test-flutter-calculator.appspot.com',
    iosBundleId: 'com.example.testCalculator',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyD3u-1f-YzT8tTNP9bDqe0Wlxt9TiFWyDQ',
    appId: '1:180029562035:ios:a08c49ec94da58d55624c6',
    messagingSenderId: '180029562035',
    projectId: 'test-flutter-calculator',
    storageBucket: 'test-flutter-calculator.appspot.com',
    iosBundleId: 'com.example.testCalculator',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAFfBUM4W4FNWFM1EXLtvmp6k-4Xtj0TO0',
    appId: '1:180029562035:web:97d8f9e25292df0a5624c6',
    messagingSenderId: '180029562035',
    projectId: 'test-flutter-calculator',
    authDomain: 'test-flutter-calculator.firebaseapp.com',
    storageBucket: 'test-flutter-calculator.appspot.com',
    measurementId: 'G-N45F0EJWBM',
  );
}
